const forumComments = [
    //comments for question 1 of general tab
    {
        id: 1,
        questionType: "general",
        questionID: 1,
        username: "",
        date: "",
        comment: "",
    },
    {
        id: 2,
        questionType: "general",
        questionID: 1,
        username: "",
        date: "",
        comment: "",
    },
    {
        id: 3,
        questionType: "general",
        questionID: 1,
        username: "",
        date: "",
        comment: "",
    },
    {
        id: 4,
        questionType: "general",
        questionID: 1,
        username: "",
        date: "",
        comment: "",
    },
    //comments for question 2 of general tab
    {
        id: 5,
        questionType: "general",
        questionID: 2,
        username: "",
        date: "",
        comment: "",
    },
    {
        id: 6,
        questionType: "general",
        questionID: 2,
        username: "",
        date: "",
        comment: "",
    },

    //comments for question 1 of classes tab
    {
        id: 7,
        questionType: "classes",
        questionID: 1,
        username: "",
        date: "",
        comment: "",
    },
    {
        id: 8,
        questionType: "classes",
        questionID: 1,
        username: "",
        date: "",
        comment: "",
    },
    {
        id: 9,
        questionType: "classes",
        questionID: 1,
        username: "",
        date: "",
        comment: "",
    },
    {
        id: 10,
        questionType: "classes",
        questionID: 1,
        username: "",
        date: "",
        comment: "",
    },
    //comments for question 2 of classes tab
    {
        id: 11,
        questionType: "classes",
        questionID: 2,
        username: "",
        date: "",
        comment: "",
    },
    {
        id: 12,
        questionType: "classes",
        questionID: 2,
        username: "",
        date: "",
        comment: "",
    },
    //comments for question 3 of classes tab
    {
        id: 13,
        questionType: "classes",
        questionID: 3,
        username: "",
        date: "",
        comment: "",
    },
    //comments for question 4 of classes tab
    {
        id: 14,
        questionType: "classes",
        questionID: 4,
        username: "",
        date: "",
        comment: "",
    },
    {
        id: 15,
        questionType: "classes",
        questionID: 4,
        username: "",
        date: "",
        comment: "",
    },
    {
        id: 16,
        questionType: "classes",
        questionID: 4,
        username: "",
        date: "",
        comment: "",
    },

    //comments for question 1 of major tab
    {
        id: 17,
        questionType: "major",
        questionID: 1,
        username: "",
        date: "",
        comment: "",
    },
    {
        id: 18,
        questionType: "major",
        questionID: 1,
        username: "",
        date: "",
        comment: "",
    },
    //comments for question 2 of major tab
    {
        id: 19,
        questionType: "major",
        questionID: 2,
        username: "",
        date: "",
        comment: "",
    },
    {
        id: 20,
        questionType: "major",
        questionID: 2,
        username: "",
        date: "",
        comment: "",
    },
    {
        id: 21,
        questionType: "major",
        questionID: 2,
        username: "",
        date: "",
        comment: "",
    },
    //comments for question 3 of major tab
    {
        id: 22,
        questionType: "major",
        questionID: 3,
        username: "",
        date: "",
        comment: "",
    },

    //comments for question 1 of social tab
    {
        id: 23,
        questionType: "social",
        questionID: 1,
        username: "",
        date: "",
        comment: "",
    },
    {
        id: 24,
        questionType: "social",
        questionID: 1,
        username: "",
        date: "",
        comment: "",
    },
    {
        id: 25,
        questionType: "social",
        questionID: 1,
        username: "",
        date: "",
        comment: "",
    },
    {
        id: 26,
        questionType: "social",
        questionID: 1,
        username: "",
        date: "",
        comment: "",
    },
    {
        id: 27,
        questionType: "social",
        questionID: 1,
        username: "",
        date: "",
        comment: "",
    },
    //comments for question 2 of social tab
    {
        id: 28,
        questionType: "social",
        questionID: 2,
        username: "",
        date: "",
        comment: "",
    },
    {
        id: 29,
        questionType: "social",
        questionID: 2,
        username: "",
        date: "",
        comment: "",
    }
]

export default forumComments;