const forumComments = [
    //comments for question 1 of general tab
    {
        id: 1,
        questionType: "general",
        questionID: 1,
        username: "",
        date: "",
        comment: "",
    },
    {
        id: 2,
        questionType: "general",
        questionID: 1,
        username: "",
        date: "",
        comment: "",
    },
    {
        id: 3,
        questionType: "general",
        questionID: 1,
        username: "",
        date: "",
        comment: "",
    },
    {
        id: 4,
        questionType: "general",
        questionID: 1,
        username: "",
        date: "",
        comment: "",
    },
    //comments for question 2 of general tab
    {
        id: 5,
        questionType: "general",
        questionID: 2,
        username: "",
        date: "",
        comment: "",
    },
    {
        id: 6,
        questionType: "general",
        questionID: 2,
        username: "",
        date: "",
        comment: "",
    },

    //comments for question 1 of classes tab
    {
        id: 7,
        questionType: "classes",
        questionID: 1,
        username: "",
        date: "",
        comment: "",
    },
    {
        id: 8,
        questionType: "classes",
        questionID: 1,
        username: "",
        date: "",
        comment: "",
    },
    {
        id: 9,
        questionType: "classes",
        questionID: 1,
        username: "",
        date: "",
        comment: "",
    },
    {
        id: 10,
        questionType: "classes",
        questionID: 1,
        username: "",
        date: "",
        comment: "",
    },
    //comments for question 2 of classes tab
    {
        id: 11,
        questionType: "classes",
        questionID: 2,
        username: "",
        date: "",
        comment: "",
    },
    {
        id: 12,
        questionType: "classes",
        questionID: 2,
        username: "",
        date: "",
        comment: "",
    },
    //comments for question 3 of classes tab
    {
        id: 13,
        questionType: "classes",
        questionID: 3,
        username: "",
        date: "",
        comment: "",
    },
    //comments for question 4 of classes tab
    {
        id: 14,
        questionType: "classes",
        questionID: 4,
        username: "",
        date: "",
        comment: "",
    },
    {
        id: 15,
        questionType: "classes",
        questionID: 4,
        username: "",
        date: "",
        comment: "",
    },
    {
        id: 16,
        questionType: "classes",
        questionID: 4,
        username: "",
        date: "",
        comment: "",
    },

    //comments for question 1 of major tab
    {
        id: 17,
        questionType: "major",
        questionID: 1,
        username: "Ribbot",
        date: "5/19/2020",
        comment: "While I do agree that a majority of bioengineers go to graduate school since it is a bit of a niche field, you should definitely consider if you would enjoy the mechE curriculum. A lot of mechE's are able to work in bioE fields since it's much easier for employers to teach mechE's bio as opposed to the technical engineering skills you acquire as a mechE",
    },
    {
        id: 18,
        questionType: "major",
        questionID: 1,
        username: "Blathers",
        date: "5/20/2020",
        comment: "I agree with Ribbot. First consider whether you enjoy the mechE curriculum, it's quite different and focuses much less on thermodynamics than the bioE curriculum does. Also, what are your reasons for avoiding grad school? Grad school could be a great option for you if that's what you want",
    },
    {
        id: 19,
        questionType: "major",
        questionID: 1,
        username: "boopboopbeep",
        date: "5/21/2020",
        comment: "Depending on what you want to go into in the bioE field (genetic engineering, medical devices, etc.) the necessity of grad school will differ. If you want to do genetic engineering where most of the work is in research, a PhD may be required.",

    },
    {
        id: 20,
        questionType: "major",
        questionID: 1,
        username: "Caroline666",
        date: "5/21/2020",
        comment:"mechE will suck the life out of you don't switch if you like to feel alive.",

    },
    //comments for question 2 of major tab
    {
        id: 21,
        questionType: "major",
        questionID: 2,
        username: "",
        date: "",
        comment: "",
    },
    {
        id: 22,
        questionType: "major",
        questionID: 2,
        username: "",
        date: "",
        comment: "",
    },
    {
        id: 23,
        questionType: "major",
        questionID: 2,
        username: "",
        date: "",
        comment: "",
    },
    //comments for question 3 of major tab
    {
        id: 24,
        questionType: "major",
        questionID: 3,
        username: "",
        date: "",
        comment: "",
    },

    //comments for question 1 of social tab
    {
        id: 25,
        questionType: "social",
        questionID: 1,
        username: "",
        date: "",
        comment: "",
    },
    {
        id: 26,
        questionType: "social",
        questionID: 1,
        username: "",
        date: "",
        comment: "",
    },
    {
        id: 27,
        questionType: "social",
        questionID: 1,
        username: "",
        date: "",
        comment: "",
    },
    {
        id: 28,
        questionType: "social",
        questionID: 1,
        username: "",
        date: "",
        comment: "",
    },
    {
        id: 29,
        questionType: "social",
        questionID: 1,
        username: "",
        date: "",
        comment: "",
    },
    //comments for question 2 of social tab
    {
        id: 30,
        questionType: "social",
        questionID: 2,
        username: "",
        date: "",
        comment: "",
    },
    {
        id: 31,
        questionType: "social",
        questionID: 2,
        username: "",
        date: "",
        comment: "",
    }
]

export default forumComments;